include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "lib/i18n/strings*.g.dart"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    cascade_invocations: false
    avoid_redundant_argument_values: false
    document_ignores: false
