import 'dart:convert';

import 'package:interfaces/cache/cache_policy.dart';

/// Cache value serializer.
abstract class CacheValueSerializer<T> {
  /// Custom type identifier.
  String get type;

  /// Serializes to a JSON-encodable object.
  dynamic toJson(T value);

  /// Deserializes from JSON.
  T fromJson(dynamic json);
}

/// Cache value serializer registry.
class CacheValueRegistry {
  final Map<Type, CacheValueSerializer> _byRuntimeType = {};
  final Map<String, CacheValueSerializer> _byTypeKey = {};

  void register<T>(CacheValueSerializer<T> serializer) {
    _byRuntimeType[T] = serializer;
    _byTypeKey[serializer.type] = serializer;
  }

  CacheValueSerializer? serializerForValue(Object value) {
    return _byRuntimeType[value.runtimeType];
  }

  CacheValueSerializer? serializerForType(String typeKey) {
    return _byTypeKey[typeKey];
  }
}

/// Cache entry.
///
/// Supports safe serialization/deserialization, handles non-JSON-compatible types,
/// and allows custom type serializers via CacheValueRegistry.
class CacheEntry {
  final String key;
  final dynamic value;
  final DateTime createdAt;
  final DateTime? expiresAt;
  final CachePolicy policy;
  DateTime lastAccessedAt;

  CacheEntry({
    required this.key,
    required this.value,
    required this.createdAt,
    this.expiresAt,
    required this.policy,
  }) : lastAccessedAt = DateTime.now();

  bool get isExpired {
    if (policy == CachePolicy.persistent) return false;
    if (expiresAt == null) return false;
    return DateTime.now().isAfter(expiresAt!);
  }

  void updateAccessTime() {
    lastAccessedAt = DateTime.now();
  }

  /// Checks whether a value can be safely serialized to JSON.
  bool get isSerializable {
    try {
      jsonEncode(_serializeValue(value));
      return true;
    } catch (_) {
      return false;
    }
  }

  /// Safely serializes to a JSON map.
  ///
  /// If value cannot be serialized, stores null and records type info.
  Map<String, dynamic> toJson({CacheValueRegistry? registry}) {
    dynamic serializedValue;
    String? valueType;

    final registrySerializer = value != null && registry != null
        ? registry.serializerForValue(value)
        : null;
    if (registrySerializer != null) {
      try {
        serializedValue = registrySerializer.toJson(value);
        valueType = registrySerializer.type;
        jsonEncode(serializedValue);
      } catch (_) {
        serializedValue = null;
        valueType = registrySerializer.type;
      }
    } else {
      try {
        serializedValue = _serializeValue(value);
        // Verify it can be encoded.
        jsonEncode(serializedValue);
      } catch (e) {
        // When unable to serialize, store null with type info.
        serializedValue = null;
        valueType = value.runtimeType.toString();
      }
    }

    return {
      'key': key,
      'value': serializedValue,
      'valueType': valueType, // Non-null when using registry or serialization failed.
      'createdAt': createdAt.toIso8601String(),
      'expiresAt': expiresAt?.toIso8601String(),
      'policy': policy.name,
    };
  }

  /// Attempts to serialize common types.
  dynamic _serializeValue(dynamic val) {
    if (val == null) return null;
    if (val is String || val is num || val is bool) return val;
    if (val is DateTime) return val.toIso8601String();
    if (val is List) return val.map(_serializeValue).toList();
    if (val is Map) {
      return val.map((k, v) => MapEntry(k.toString(), _serializeValue(v)));
    }
    // Try calling toJson (e.g. classes generated by freezed/json_serializable).
    if (val is Object) {
      try {
        final dynamic toJsonMethod = (val as dynamic).toJson;
        if (toJsonMethod != null) {
          return toJsonMethod();
        }
      } catch (_) {
        // No toJson method, return raw value for jsonEncode to handle.
      }
    }
    return val;
  }

  factory CacheEntry.fromJson(
    Map<String, dynamic> json, {
    CacheValueRegistry? registry,
  }) {
    final valueType = json['valueType'] as String?;
    dynamic value = json['value'];

    if (valueType != null && registry != null) {
      final serializer = registry.serializerForType(valueType);
      if (serializer != null) {
        try {
          value = serializer.fromJson(value);
        } catch (_) {
          // fallback to raw value
        }
      }
    }

    return CacheEntry(
      key: json['key'],
      value: value, // May be null if the original value cannot be serialized.
      createdAt: DateTime.parse(json['createdAt']),
      expiresAt: json['expiresAt'] != null
          ? DateTime.parse(json['expiresAt'])
          : null,
      policy: CachePolicy.values.firstWhere(
        (e) => e.name == json['policy'],
        orElse: () => CachePolicy.normal,
      ),
    );
  }
}
